### ISSUE TITLE
AWS SSO renamed to AWS IAM Identity Center

### ISSUE THREAD

**Issue by allquixotic** [aws-samples/aws-iam-identity-center-extensions#99]
Should go through code comments, documentation, examples, etc. for SSO Extensions and update it to account for the rename. I don't think any links or low level API changes occurred with the rename, and all the resources, in IAM, etc. continue to reference `sso:`, `identitystore:`, etc. so we shouldn't have to adjust any code.

I wonder if this is heralding an incoming CRUD API other than SCIM for users... :)

**Comment by leelalagudu** [comment]
Yep, seen this release announcement. As you can imagine this would be a lower priority change Sean :) . I think so too, may be there's a CRUD API release announcement not in the too distant future :):) 

Also, just as an FYI - we are in progress towards working on enabling support for customer managed policies and permission boundaries as well. Currently working on a fix due to https://github.com/aws/aws-sdk-js-v3/issues/3822 , and when the work around is implemented, we will be releasing support for both customer managed policies and permission sets.

**Comment by allquixotic** [comment]
RE: this issue being low priority

Not a problem. I don't expect it to be a priority at all, just thought it would be good to add it to the issue tracker. 


RE: customer managed policies and permission boundaries 

Awesome! All these really useful features are coming out right as my customer and I are launching AWS SSO based on the old featureset. I designed a fairly complex, Trie-based IAM policy "compression" algorithm that minimizes IAM statements to the bare minimum because so many of our policies were > 10240 chars... now with customer managed policies, we could have improved this situation without compression. Oh well :)
